import { FluentProvider, createLightTheme, type BrandVariants } from '@fluentui/react-components';
import { BrowserRouter, Link, Route, Routes, useLocation } from 'react-router-dom';
import { HomeRegular, HistoryRegular, ShieldCheckmarkRegular, ArrowUploadRegular, SearchRegular } from '@fluentui/react-icons';
import { createRoot } from 'react-dom/client';
import { useEffect, useState } from 'react';
import { api } from './api';
import type { Analysis } from './types';
import './styles.css';
import { AudioPanel } from './AudioPanel';

const brand: BrandVariants = {10:'#001d1b',20:'#003330',30:'#004c48',40:'#006560',50:'#087b74',60:'#0b6e69',70:'#23867f',80:'#499b94',90:'#70afa8',100:'#8ebfba',110:'#acd0cb',120:'#c4dedb',130:'#d9e9e7',140:'#e8f2f0',150:'#f1f8f7',160:'#f8fbfa'};
const theme = createLightTheme(brand);
const riskTone = (score: number) => score >= 65 ? 'high' : score >= 40 ? 'medium' : 'low';

function Shell() { const location = useLocation(); return <div className="shell"><header className="topbar"><div className="brand"><span className="brand-mark"><ShieldCheckmarkRegular /></span><span>DeepGuard</span><small>BẢNG ĐIỀU KHIỂN PHÂN TÍCH</small></div><nav><Link className={location.pathname==='/'?'active':''} to="/"><HomeRegular /> Phân tích</Link><Link className={location.pathname==='/history'?'active':''} to="/history"><HistoryRegular /> Lịch sử</Link></nav><div className="operator"><span className="status-dot"/> PHIÊN LOCAL <b>DG</b></div></header><Routes><Route path="/" element={<Analyze />} /><Route path="/history" element={<History />} /></Routes></div> }

function Hero() { return <section className="hero"><div className="hero-copy"><p className="eyebrow"><span/> PHÂN TÍCH NỘI DUNG GIẢ</p><h1>Nhìn thấy tín hiệu<br/><em>đằng sau nội dung.</em></h1><p>DeepGuard chuyển dấu vết trong văn bản và media thành kết quả rủi ro rõ ràng, dễ kiểm tra. Mỗi kết quả là một manh mối heuristic, không phải phán quyết dạng black box.</p><div className="hero-actions"><a className="button primary" href="#workspace"><ArrowUploadRegular /> Bắt đầu phân tích</a><a className="button ghost" href="#method">Xem phương pháp <SearchRegular /></a></div></div><div className="hero-metrics"><strong>04</strong><span>CHẾ ĐỘ<br/>HỖ TRỢ</span><i/><strong>LOCAL</strong><span>DỮ LIỆU CỦA BẠN<br/>Ở ĐÂY</span></div></section> }

function StatusView({ state, retry }: { state: 'loading'|'error'|'empty'|'data'; retry:()=>void }) { if(state==='loading') return <div className="state"><div className="skeleton"/><div className="skeleton short"/></div>; if(state==='error') return <div className="state error"><b>Không thể tải lịch sử cục bộ.</b><button onClick={retry}>Thử lại</button></div>; if(state==='empty') return <div className="state"><b>Chưa có phát hiện nào.</b><span>Chạy phân tích đầu tiên để tạo dữ liệu cho không gian làm việc.</span></div>; return null; }
function FindingCard({ item }: { item: Analysis }) { return <article className="finding"><div className="finding-head"><span className={`modality ${item.modality.toLowerCase()}`}>{item.modality}</span><span className={`risk ${riskTone(item.riskScore)}`}>{item.riskScore} <small>/ 100</small></span></div><h3>{item.input}</h3><p>{item.label} <span>·</span> {Math.round(item.confidence*100)}% {item.modality === 'Audio' ? 'điểm mô hình (chưa hiệu chỉnh)' : 'độ tin cậy'}</p><div className="bar"><i style={{width:`${item.riskScore}%`}}/></div><footer><span>{item.detector}</span><time>{item.createdAt}</time></footer></article> }
function Analyze() { const [text,setText]=useState(''); const [items,setItems]=useState<Analysis[]>([]); const [state,setState]=useState<'loading'|'error'|'empty'|'data'>('loading'); const [result,setResult]=useState<Analysis>(); useEffect(()=>{ api.listAnalyses().then(data=>{setItems(data);setState(data.length?'data':'empty');}).catch(()=>setState('error')); },[]); const submit=async()=>{if(!text.trim())return;setResult(await api.analyzeText(text));}; return <main><Hero/><AudioPanel/><section className="workspace" id="workspace"><div className="section-label"><span>01</span><div><p className="eyebrow">KHÔNG GIAN PHÂN TÍCH</p><h2>Đưa bằng chứng của bạn.</h2></div><span className="contract">HEURISTIC MVP <b>●</b></span></div><div className="workspace-grid"><div className="panel form-panel"><div className="tabs"><button className="selected">Văn bản</button><button>Hình ảnh</button><button onClick={() => document.getElementById('audio-workspace')?.scrollIntoView({ behavior: 'smooth' })}>Âm thanh</button><button>Video</button></div><label htmlFor="evidence">BẰNG CHỨNG VĂN BẢN <span>Bắt buộc</span></label><textarea id="evidence" value={text} onChange={e=>setText(e.target.value)} placeholder="Dán đoạn văn bản, câu nói hoặc bản ghi âm..."/><div className="field-note">{text.length}/5000 ký tự <span>Chỉ văn bản thuần</span></div>{!text && <div className="validation">Thêm bằng chứng trước khi chạy bộ phát hiện.</div>}<button className="button primary full" onClick={submit} disabled={!text.trim()}>Chạy bộ phát hiện <ArrowUploadRegular /></button>{result && <div className="result"><b>{result.label}</b><strong>{result.riskScore}<small>/100</small></strong></div>}</div><div className="findings"><div className="panel-title"><div><p className="eyebrow">PHÁT HIỆN GẦN ĐÂY</p><h2>Phiên cục bộ</h2></div><Link to="/history">Xem tất cả <span>→</span></Link></div><StatusView state={state} retry={()=>{setState('loading');api.listAnalyses().then(data=>{setItems(data);setState('data')}).catch(()=>setState('error'))}}/><div className="finding-list">{state==='data'&&items.slice(0,3).map(item=><FindingCard key={item.analysisId} item={item}/>)}</div></div></div></section></main> }
function History() { const [items,setItems]=useState<Analysis[]>([]); useEffect(()=>{api.listAnalyses().then(setItems)},[]); return <main className="history-page"><div className="page-heading"><p className="eyebrow">LỊCH SỬ PHÂN TÍCH</p><h1>Mọi phát hiện, <em>đều có thể truy vết.</em></h1><p>Hồ sơ phiên cục bộ từ hệ thống heuristic của DeepGuard.</p></div><div className="table-wrap"><table><thead><tr><th>ID</th><th>CHẾ ĐỘ</th><th>ĐẦU VÀO</th><th>NHÃN</th><th>RỦI RO</th><th>THỜI GIAN</th></tr></thead><tbody>{items.map(item=><tr key={item.analysisId}><td>{item.analysisId}</td><td><span className={`modality ${item.modality.toLowerCase()}`}>{item.modality}</span></td><td>{item.input}</td><td>{item.label}</td><td><b className={`risk-text ${riskTone(item.riskScore)}`}>{item.riskScore}</b></td><td>{item.createdAt}</td></tr>)}</tbody></table></div></main> }
function App(){return <FluentProvider theme={theme}><BrowserRouter><Shell/></BrowserRouter></FluentProvider>};

export default App;

createRoot(document.getElementById('root')!).render(<App />);
